### PR TITLE
Don't extract links as arbitrary properties

### LINKED ISSUE #17128: Bug: [url] in typescript comments causing Unclosed block errors
**What version of Tailwind CSS are you using?**

@tailwindcss/postcss v4.0.10+

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 15.2.2

**What version of Node.js are you using?**

v22.14.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/mhornbacher/tailwind-repro

**Details**
Since version 4.0.10, `/**/` style comments in `.ts` files containing `[url]` syntax generate the following build error:

```
HookWebpackError: /Users/menachem/dev/bugs/tailwind-repro/static/css/299a46ed717ed6dc.css:46:4146: Unclosed block
```

For instance, adding a file like this anywhere in the source code triggers a crash that is challenging to debug:

```
// junk.ts
/* 
  add a url here [https://github.com/arasatasaygin/is.js]
*/
export function junk() {
  return 1 + 1;
}
```

To identify this issue, it is recommended to utilize the `@tailwindcss/cli` to generate an output and subsequently search it for the URL.

The commit that appears most relevant to this issue is: https://github.com/tailwindlabs/tailwindcss/commit/b3c25563b7bf9c9908352523f4fa2c795d06e075

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #17128

This PR prevents extraction of links inside square brackets as valid candidate:

```
[https://example/]
```

We do this by throwing out arbitrary properties when the value starts with a slash (`/`).

## Test plan

- Added unit test

### CODE REVIEW

File: crates/oxide/src/extractor/arbitrary_property_machine.rs [hunk 1]
```diff
@@ -163,6 +163,7 @@ impl Machine for ArbitraryPropertyMachine<ParsingValueState> {
     #[inline]
     fn next(&mut self, cursor: &mut cursor::Cursor<'_>) -> MachineState {
         let len = cursor.input.len();
+        let start_of_value = cursor.pos;
```
Comment (RobinMalfait) [inline crates/oxide/src/extractor/arbitrary_property_machine.rs:166]:
```suggestion
        let start_of_value_pos = cursor.pos;
```

File: crates/oxide/src/extractor/arbitrary_property_machine.rs [hunk 2]
```diff
@@ -222,6 +223,9 @@ impl Machine for ArbitraryPropertyMachine<ParsingValueState> {
                 // Any kind of whitespace is not allowed
                 Class::Whitespace => return self.restart(),
 
+                // URLs are not allowed
+                Class::Slash if start_of_value == cursor.pos => return self.restart(),
```
Comment (RobinMalfait) [inline crates/oxide/src/extractor/arbitrary_property_machine.rs:227]:
```suggestion
                Class::Slash if start_of_value_pos == cursor.pos => return self.restart(),
```

**Review by RobinMalfait — APPROVED** [review]
