### PR TITLE
Fix "Maximum call stack size exceeded" bug

### LINKED ISSUE #8582: Maximum call stack size exceeded
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/8578

<div type='discussions-op-text'>

<sup>Originally posted by **jithureddy** June 10, 2022</sup>
Hi, Please help

Just updated my project to latest `"tailwindcss": "^3.1.1"` and using create react app setup from here. It was working great with  `"tailwindcss": "^3.0.4"`.

```
tailwind.config.js - 

const deepMerge = require('deepmerge')
const formsPlugin = require('@tailwindcss/forms')
const { fontFamily } = require('tailwindcss/defaultTheme')
const colors = require('./colors')

const uiConfig = {
	content: [
		'node_modules/@mondra/ui-components/dist/index.js',
		'./src/**/*.{html,js,jsx,ts,tsx}',
	],
	theme: {
		colors,
		container: {
			padding: '2rem',
		},
		extend: {
			animation: {
				'fade-in': 'fade-in 200ms ease-in-out',
				overlay: 'overlay 200ms ease-in-out',
				'slide-down': 'slide-down 150ms ease-in',
			},
			boxShadow: {
				focus: '#ffffff 0px 0px 0px 0px, #6366f1 0px 0px 0px 2px, rgba(0, 0, 0, 0.05) 0px 1px 2px 0px',
			},
			gridColumn: {
				'span-13': 'span 13 / span 13',
				'span-14': 'span 14 / span 14',
				'span-15': 'span 15 / span 15',
				'span-16': 'span 16 / span 16',
				'span-17': 'span 17 / span 17',
				'span-18': 'span 18 / span 18',
				'span-19': 'span 19 / span 19',
				'span-20': 'span 20/ span 20',
			},
			height: {
				'app-header': '56px',
				'brand-logo': '150px',
				'card-header': '56px',
			},
			keyframes: {
				'fade-in': {
					'0%': {
						opacity: 0,
					},
					'100%': { opacity: 1 },
				},
				overlay: {
					'0%': {
						opacity: 0,
					},
					'100%': { opacity: 0.75 },
				},
				'slide-down': {
					'0%': {
						opacity: 0,
						transform: 'translateY(-10px)',
					},
					'100%': { opacity: 1, transform: 'translateY(0)' },
				},
			},
			maxHeight: {
				'dropdown-list': '40vh',
				'scroll-height': 'calc(100vh - 56px)',
			},
			maxWidth: {
				'company-selection': '150px',
				'sidebar-close': '80px',
				'sidebar-open': '256px',
			},
			minHeight: {
				button: '32px',
				'scroll-height': 'calc(100vh - 56px)',
			},
			minWidth: {
				12: '48px',
				'sidebar-close': '80px',
				'sidebar-open': '256px',
			},
			opacity: {
				80: '0.8',
			},
			screens: {
				xxl: { min: '1600px' },
			},
			spacing: {
				14: '3.5rem',
			},
			width: {
				31: '6rem',
				'brand-logo': '180px',
				'fit-content': 'fit-content',
				'sidebar-close': '80px',
				'sidebar-open': '256px',
			},
			zIndex: {
				'-1': -1,
				dialog: 9999,
				px: 1,
				slideover: 60,
				toast: 10000,
			},
		},
		fontFamily: {
			inter: ['Inter', ...fontFamily.sans],
		},
	},
	plugins: [formsPlugin],
}

function arrayMergeFn(destinationArray, sourceArray) {
	return destinationArray.concat(sourceArray).reduce((acc, cur) => {
		if (acc.includes(cur)) return acc
		return [...acc, cur]
	}, [])
}

/**
 * Merge UI components config and Tailwind CSS configurations
 * @param {object} tailwindConfig - Tailwind config object
 * @return {object} new config object
 */
function wrapper(tailwindConfig) {
	return deepMerge({ ...tailwindConfig }, uiConfig, {
		arrayMerge: arrayMergeFn,
	})
}

module.exports = wrapper
```

image
</div>

### PR DESCRIPTION
**Pull request by adamwathan**
For performance reasons we already read the content line by line, this allows us to cache individual lines if we already saw them. This also allows us to do the necessary work on relatively "small" content chunks because not a lot of developers use very long lines in the source files.

However...

Some people either misconfigure the `content` paths to include everything (even node_modules) or in a more realistic scenario link to a 3rd party dependency that uses Tailwind inside the node_modules folder. Those files are typically minified, all on one line. The stack size issue occurs when we try to push a lot of matches into an array. We used `result.push(...x)` which is limited by the length of `x` because functions have a maximum amount of parameters they can receive.

Thanks to @nam-tran-tego for the wonderful reproduction and fix for this!

Fixes: #8582

### CODE REVIEW

File: src/lib/defaultExtractor.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ export function defaultExtractor(context) {
     let results = []
 
     for (let pattern of patterns) {
-      results.push(...(content.match(pattern) ?? []))
+      results = [...results, ...(content.match(pattern) ?? [])]
```
Comment (MichaelAllenWarner) [inline src/lib/defaultExtractor.js:15]: I don't really know the context here, but if performance is at all relevant, then you might consider doing something like this instead:

```javascript
for (let pattern of patterns) {
  for (let result of (content.match(pattern) || [])) {
    results.push(result);
  }
}
```

(didn't test it or anything, so apologies if that isn't quite right, but the point is that there's no need to iterate through `results` on every iteration of `patterns`; same principle as in this piece: https://betterprogramming.pub/the-reduce-spread-anti-pattern-fc0c1c0b23f6)

Comment (thecrypticace) [reply src/lib/defaultExtractor.js:15]: I looked into this a bit and there's very little perf difference (in a plain program at least) when given a super large content array. There's a slight difference in heap allocations but it's tiny. The perf difference is on the order of ± 0.1ms for 1000 iterations.

Though, my testing method could be a bit flawed or V8 may have hyper optimized my test case. Either way I think it's not a big deal one way or the other.

Comment (MichaelAllenWarner) [reply src/lib/defaultExtractor.js:15]: Huh. I'd be surprised if there's really no significant difference, since pushing only the new items each time is O(n), whereas _also_ iterating through all previously added items each time is O(n^2-ish). But yeah, could be that they've optimized it. Cheers.

Comment (thecrypticace) [reply src/lib/defaultExtractor.js:15]: This is because array's in V8 are likely tail-allocated. This means doing something like `result = [...result, ...anything]` makes only a constant number of allocations independent of the number of items in `result`. Only the number of items in `anything` matters. If you flip the arrays around (`result = [...anything, ...result]`) it can't reuse existing memory/storage and must copy memory around. If you try this it results in times that are almost 4x slower.
