### PR TITLE
Fix variants with `<digit>.</digit>` are extracted correctly

### LINKED ISSUE #17148: Version > 4.0.11 do not recognize dots in the custom screens breakpoints
It seems that from version `4.0.12` (included), any custom screen breakpoint (for example `1.5md`) that contains a dot is not recognized.

**What version of Tailwind CSS are you using?**

For example: v4.0.13

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: Vite 5.4.14

**What version of Node.js are you using?**

For example: v22

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: macOS

**Describe your issue**

Using a `tailwind.config.ts` file, and using the config below it does not recognize the breakpoints with a dot. It was doing it for the previous version.

```typescript
export default {
        ...
	theme: {
		...
		screens: {
			...
			// custom viewports
			'1.5md': '896px',
			'1.5lg': '1152px',
			'1.5xl': '1408px',
			'2.5xl': '1728px',
		},
		...
	},
	...
} satisfies Config;

```

### PR DESCRIPTION
**Pull request by RobinMalfait**
This PR fixes an issue where if you use a number with a decimal in a variant then it wasn't picked up correctly.

E.g.:
```
<div class="2xl:flex 1.5xl:flex"></div>
            ^^^^^^^^                        Picked up
                     ^^^^^^^^^^             Not picket up
```

This PR fixes that behavior by applying the same rules for utilities where a `.` is valid if it is surrounded by numbers.

# Test plan

1. Added test to ensure this is picked up
2. Existing tests pass
3. Ran the extractor on a real example with the following results:

| Before | After |
| --- | --- |
| image | image |

They are crossed out just because it's not a default value we know in the system, but you can see that the `1.` part is also extracted now.

Fixes: #17148

### CODE REVIEW

File: crates/oxide/src/extractor/named_variant_machine.rs [hunk 1]
```diff
@@ -235,6 +235,22 @@ impl Machine for NamedVariantMachine<ParsingState> {
                 //             ^
                 Class::Colon => return self.done(self.start_pos, cursor),
 
+                // A dot must be surrounded by numbers
+                //
+                // E.g.: `px-2.5`
```
Comment (adamwathan) [inline crates/oxide/src/extractor/named_variant_machine.rs:240]: Should we use a variant example here instead of a utility value example?

Comment (RobinMalfait) [reply crates/oxide/src/extractor/named_variant_machine.rs:240]: Copy paste before going to the gym oops. Will fix, thanks!

**Review by thecrypticace — APPROVED** [review]
lgtm (aside from the comment)
