### PR TITLE
Don't wrap relative selectors in arbitrary variants with `:is(…)`

### LINKED ISSUE #14202: `has-*` with relative selector produces wrong output
**What version of Tailwind CSS are you using?**

tailwindcss v4.0.0-alpha.19

**What build tool (or framework if it abstracts the build tool) are you using?**

`@tailwindcss/cli@4.0.0-alpha.19`

**What version of Node.js are you using?**

v20.12.2

**What browser are you using?**

Chrome version 127.0.6533.89 (Official Build) (arm64)

**What operating system are you using?**

macOS 14.5

**Reproduction URL**

https://play.tailwindcss.com/eVAnr2RUDF

**Describe your issue**

Element with `has-[>img]:bg-red-500` should only have red background when it has an immediate child that is an ``.

However, the generated output is

image

With `has-[&>img]:bg-red-500`, the outer container has red background, even though its immediate children is the one that has immediate ``. The output of that is:

image

What I would expect it to output:

```css
.has-\[\>img\]\:bg-red-500 {
  &:has(>img) {
    background-color: var(--color-red-500, #ef4444);
  }
}
```

For the case of `has-[&>img]:bg-red-500`, it should probably output the same as above, since `&>img` is not really a [relative selector](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/Selector_structure#relative_selector)

### PR DESCRIPTION
**Pull request by adamwathan**
Prior to this PR, we weren't accounting for the fact that `:has(…)` supports [relative selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/Selector_structure#relative_selector), which are sort of like partial selectors that can start with a combinator like `>`, `+`, or `~`.

Before, a class like `has-[>img]:flex` would generate this:

```css
.has-\[\>img\]\:flex:has(*:is(> img)) {
  display: flex;
}
```

This was incorrect because `*:is(> img)` isn't even valid CSS at all, so the rule would do nothing.

After this change, we generate this instead:

```css
.has-\[\>img\]\:flex:has(> img) {
  display: flex;
}
```

This PR also ensures that relative selectors are recognized as invalid in places where they are not supported, so classes like `group-[>img]:flex` for example will produce nothing now instead of invalid CSS.

This is mostly a simple change but it did involve storing some additional information in the variant AST.

Fixes #14202.

### CODE REVIEW

**Review by thecrypticace — APPROVED** [review]

File: packages/tailwindcss/src/candidate.ts [hunk 1]
```diff
@@ -510,21 +514,23 @@ export function parseVariant(variant: string, designSystem: DesignSystem): Varia
...
-      }
+    let relative = selector[0] === '>' || selector[0] === '+' || selector[0] === '~'
+
+    // Ensure `&` is always present by wrapping the selector in `&:is(…)`,
+    // unless it's a relative selector like `> img`.
+    //
+    // E.g.:
+    //
+    // - `[p]:flex`
+    if (selector[0] !== '@' && !selector.includes('&') && !relative) {
```
Comment (RobinMalfait) [inline packages/tailwindcss/src/candidate.ts:525]: Big nitpick: teeny tiny micro optimization, but feels conceptually more correct to me:
```suggestion
    if (!relative && selector[0] !== '@' && !selector.includes('&')) {
```

I think it's worth checking for the simple boolean first, before checking anything related to the string.

**Review by RobinMalfait — APPROVED** [review]

**Review by philipp-spiess — APPROVED** [review]

File: packages/tailwindcss/src/candidate.ts (hunk 1 above)
Comment (adamwathan) [reply packages/tailwindcss/src/candidate.ts]: Agree!
