### PR TITLE
Fix IntelliSense class suggestions

### LINKED ISSUE #1133: `--*: initial;` and `--spacing-*: initial;` doesn't remove default theme spacing classes or font classes
**What version of VS Code are you using?**

For example: v1.96.4

**What version of Tailwind CSS IntelliSense are you using?**

0.14.1

**What version of Tailwind CSS are you using?**
4.0.0

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Describe your issue**

In my global.css I have 

```
@import 'tailwindcss';

@plugin 'tailwindcss-react-aria-components';

@theme {
	--text-*: initial;
	--spacing-*: initial;
	--font-*: initial;
	--font-weight-*: initial;

	--font-sans: var(--font-sans);
	--font-mono: var(--font-mono);

	--font-weight-normal: 400;
	--font-weight-medium: 700;
	--font-weight-bold: 900;

	/* @link https://utopia.fyi/type/calculator?c=320,16,1.125,1240,18,1.2,5,2,&s=0.75|0.5|0.25,1.5|2|3|4|6,s-l&g=s,l,xl,12 */
	--text--2: clamp(0.7813rem, 0.7932rem + -0.0154vw, 0.7901rem);
	--text--1: clamp(0.8889rem, 0.872rem + 0.0845vw, 0.9375rem);
	--text-0: clamp(1rem, 0.9565rem + 0.2174vw, 1.125rem);
	--text-1: clamp(1.125rem, 1.0467rem + 0.3913vw, 1.35rem);
	--text-2: clamp(1.2656rem, 1.1424rem + 0.6163vw, 1.62rem);
	--text-3: clamp(1.4238rem, 1.2429rem + 0.9046vw, 1.944rem);
	--text-4: clamp(1.6018rem, 1.3475rem + 1.2713vw, 2.3328rem);
	--text-5: clamp(1.802rem, 1.4551rem + 1.7345vw, 2.7994rem);

	/* @link https://utopia.fyi/space/calculator?c=320,16,1.125,1240,18,1.2,5,2,&s=0.75|0.5|0.25,1.5|2|3|4|6,s-l&g=s,l,xl,12 */
	--spacing-3xs: clamp(0.25rem, 0.2283rem + 0.1087vw, 0.3125rem);
	--spacing-2xs: clamp(0.5rem, 0.4783rem + 0.1087vw, 0.5625rem);
	--spacing-xs: clamp(0.75rem, 0.7065rem + 0.2174vw, 0.875rem);
	--spacing-s: clamp(1rem, 0.9565rem + 0.2174vw, 1.125rem);
	--spacing-m: clamp(1.5rem, 1.4348rem + 0.3261vw, 1.6875rem);
	--spacing-l: clamp(2rem, 1.913rem + 0.4348vw, 2.25rem);
	--spacing-xl: clamp(3rem, 2.8696rem + 0.6522vw, 3.375rem);
	--spacing-2xl: clamp(4rem, 3.8261rem + 0.8696vw, 4.5rem);
	--spacing-3xl: clamp(6rem, 5.7391rem + 1.3043vw, 6.75rem);

	/* One-up pairs */
	--spacing-3xs-2xs: clamp(0.25rem, 0.1413rem + 0.5435vw, 0.5625rem);
	--spacing-2xs-xs: clamp(0.5rem, 0.3696rem + 0.6522vw, 0.875rem);
	--spacing-xs-s: clamp(0.75rem, 0.6196rem + 0.6522vw, 1.125rem);
	--spacing-s-m: clamp(1rem, 0.7609rem + 1.1957vw, 1.6875rem);
	--spacing-m-l: clamp(1.5rem, 1.2391rem + 1.3043vw, 2.25rem);
	--spacing-l-xl: clamp(2rem, 1.5217rem + 2.3913vw, 3.375rem);
	--spacing-xl-2xl: clamp(3rem, 2.4783rem + 2.6087vw, 4.5rem);
	--spacing-2xl-3xl: clamp(4rem, 3.0435rem + 4.7826vw, 6.75rem);

	/* Custom pairs */
	--spacing-s-l: clamp(1rem, 0.5652rem + 2.1739vw, 2.25rem);
}
```

When I use `--text-*: initial` it removes default text sizing utilities however `--spacing-*: initial` doesn't remove default spacing utilities for padding, margins, space etc. Tailwind doesn't generate old classes for example px-2 doesn't work but it still shows up in suggestions.

I also noticed `--font-*: initial;`, `--font-weight-*: initial;` don't remove default utility suggestions either. 

`--*: initial;` should remove all default theme classes where necessary.

### LINKED ISSUE #1136: [v4] Intellisense auto-complete not working for `@container` variants
**What version of VS Code are you using?**

v1.96.4

**What version of Tailwind CSS IntelliSense are you using?**

v0.14.1

**What version of Tailwind CSS are you using?**

v4.0.0

**What package manager are you using?**

bun v1.2

**What operating system are you using?**

Windows

**Tailwind config**

```css
@import 'tailwindcss';
```

**VS Code settings**

<details><summary>Details</summary>
<p>

```json
{
  "css.lint.unknownAtRules": "ignore",
  "less.lint.unknownAtRules": "ignore",
  "scss.lint.unknownAtRules": "ignore",
  "diffEditor.diffAlgorithm": "advanced",
  "editor.bracketPairColorization.independentColorPoolPerBracketType": true,
  "editor.cursorWidth": 2,
  "editor.dragAndDrop": false,
  "editor.inlayHints.enabled": "off",
  "editor.inlineSuggest.enabled": true,
  "editor.minimap.renderCharacters": false,
  "editor.minimap.showSlider": "always",
  "explorer.compactFolders": false,
  "explorer.confirmDelete": false,
  "files.insertFinalNewline": true,
  "files.simpleDialog.enable": true,
  "github.copilot.enable": {
    "*": true,
    "plaintext": true,
    "markdown": true,
    "scminput": false
  },
  "highlight-matching-tag.highlightFromContent": true,
  "highlight-matching-tag.highlightSelfClosing": true,
  "highlight-matching-tag.styles": {
    "opening": {
      "name": {
        "highlight": "rgba(255, 255, 255, 0.05)",
        "underline": "cyan"
      }
    }
  },
  "html.format.indentInnerHtml": true,
  "html.format.templating": true,
  "intelephense.stubs": [
    "apache",
    "bcmath",
    "bz2",
    "calendar",
    "com_dotnet",
    "Core",
    "ctype",
    "curl",
    "date",
    "dba",
    "dom",
    "enchant",
    "exif",
    "FFI",
    "fileinfo",
    "filter",
    "fpm",
    "ftp",
    "gd",
    "gettext",
    "gmp",
    "hash",
    "iconv",
    "imap",
    "intl",
    "json",
    "ldap",
    "libxml",
    "mbstring",
    "meta",
    "mysqli",
    "oci8",
    "odbc",
    "openssl",
    "pcntl",
    "pcre",
    "PDO",
    "pdo_ibm",
    "pdo_mysql",
    "pdo_pgsql",
    "pdo_sqlite",
    "pgsql",
    "Phar",
    "posix",
    "pspell",
    "random",
    "readline",
    "Reflection",
    "session",
    "shmop",
    "SimpleXML",
    "snmp",
    "soap",
    "sockets",
    "sodium",
    "SPL",
    "sqlite3",
    "standard",
    "superglobals",
    "sysvmsg",
    "sysvsem",
    "sysvshm",
    "tidy",
    "tokenizer",
    "wordpress",
    "xml",
    "xmlreader",
    "xmlrpc",
    "xmlwriter",
    "xsl",
    "Zend OPcache",
    "zip",
    "zlib"
  ],
  "material-icon-theme.saturation": 0.9,
  "svg.preview.autoShow": true,
  "svg.preview.mode": "svg",
  "telemetry.telemetryLevel": "error",
  "totalTypeScript.hideAllTips": false,
  "totalTypeScript.hideBasicTips": true,
  "totalTypeScript.hiddenTips": [
    "passing-generics-to-types",
    "typeof",
    "generic-slots-in-functions",
    "tuple-type",
    "omit-utility-type",
    "non-null-expression",
    "interface-with-generics",
    "record-utility-type",
    "never-keyword",
    "type-alias-with-generics",
    "mapped-type",
    "keyof",
    "returntype-utility-type",
    "awaited-utility-type",
    "type-alias-with-multiple-generics",
    "extract-utility-type",
    "conditional-type",
    "nested-conditional-type",
    "infer"
  ],
  "terminal.explorerKind": "external",
  "terminal.external.windowsExec": "C:\\Users\\[omitted]\\AppData\\Local\\Microsoft\\WindowsApps\\wt.exe",
  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.cursorStyle": "line",
  "terminal.integrated.cursorWidth": 1,
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "terminal.integrated.enableMultiLinePasteWarning": "auto",
  "terminal.integrated.fontFamily": "Inconsolata",
  "terminal.integrated.fontSize": 16,
  "terminal.integrated.fontWeight": "400",
  "terminal.integrated.profiles.windows": {
    "Cmder": {
      "args": ["/k", "${env:cmder_root}\\vendor\\bin\\vscode_init.cmd"],
      "color": "terminal.ansiGreen",
      "icon": "terminal-bash",
      "name": "Cmder",
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ]
    }
  },
  "window.dialogStyle": "custom",
  "window.newWindowDimensions": "inherit",
  "workbench.iconTheme": "material-icon-theme",
  "workbench.list.horizontalScrolling": true,
  "workbench.list.smoothScrolling": true,
  "workbench.tree.indent": 12,
  "workbench.view.alwaysShowHeaderActions": true,
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[scss]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[markdown]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "vue.updateImportsOnFileMove.enabled": true,
  "git.openRepositoryInParentFolders": "never",
  "redhat.telemetry.enabled": false,
  "gitlens.terminal.overrideGitEditor": false,
  "colorize.languages": [
    "css",
    "tailwindcss",
    "javascript",
    "typescript",
    "vue"
  ],
  "workbench.colorTheme": "Material Syntax - Dark",
  "explorer.confirmDragAndDrop": false,
  "window.commandCenter": false,
  "security.allowedUNCHosts": ["wsl.localhost"],
  "git.autofetch": true,
  "vscode-color-picker.languages": [
    "css",
    "tailwindcss",
    "python",
    "javascript",
    "typescript",
    "vue"
  ],
  "editor.stickyScroll.defaultModel": "foldingProviderModel",
  "editor.stickyScroll.maxLineCount": 10,
  "workbench.tree.stickyScrollMaxItemCount": 15,
  "errorLens.messageTemplate": "($count) $message",
  "errorLens.delayMode": "debounce",
  "vue.inlayHints.missingProps": true,
  "vue.splitEditors.layout.right": ["template", "customBlocks"],
  "editor.smoothScrolling": true,
  "editor.fontFamily": "'Consolas', 'monospace', monospace",
  "settingsSync.ignoredSettings": ["editor.fontFamily"],
  "window.menuBarVisibility": "compact",
  "github.copilot.editor.enableAutoCompletions": true,
  "git.confirmSync": false,
  "terminal.integrated.shellIntegration.enabled": false,
  "javascript.updateImportsOnFileMove.enabled": "never",
  "files.associations": {
    "*.ts": "typescript",
    "*.css": "css"
  },
  "terminal.integrated.scrollback": 3000,
  "terminal.integrated.env.windows": {},
  "editor.gotoLocation.multipleDefinitions": "goto",
  "vue.server.hybridMode": true,
  "php.validate.executablePath": "[omitted]\\php.exe",
  "security.promptForLocalFileProtocolHandling": false,
  "cSpell.userWords": [
    // omitted
  ],
  "cSpell.language": "en,pt-BR",
  "cSpell.ignoreWords": [
    // omitted
  ],
}

```

</p>
</details> 

**Reproduction URL**

https://github.com/ojvribeiro/tailwind-intellisense-repro

**Describe your issue**

In a fresh minimal project (React or Vue), intellisense auto-complete is not working for `@container` variants like `@sm` or `@md`. On hover I still get the popover:

https://github.com/user-attachments/assets/84d20fbc-9e9b-4d93-927d-e7392932aad6

### LINKED ISSUE #15811: Can't unset font-weights in v4
**What version of Tailwind CSS are you using?**

v4.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

vite v6.0.3

**What version of Node.js are you using?**

v20.13.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Describe your issue**

I just started to use tailwind (jumped straight to v4) and I'm building my existing design system under my css file. I'm not sure what I'm doing wrong but I tried plenty of options and I just cant to unset all the existing tailwind's font-weights.
```css
@theme {
    /* tried to unset this */
    --font-*: initial;
    /* and also this */
    --font-weight-*: initial;

    --font-weight-extraBold: 800;
    --font-weight-bold: 700;
    --font-weight-semiBold: 600;
    --font-weight-normal: 400;
}
```

here it what I get on intellisense, it even multiplies the stuff

Image

### PR DESCRIPTION
**Pull request by thecrypticace**
This PR fixes a few problems with IntelliSense:
- Default installs suggest font weight utilities twice
- When setting `--font-weight-*: initial;` the default weights are still suggested
- Setting `--spacing-*: initial;` still shows suggestions for utilities using the spacing scale assuming it's multiplier-based. Removing the `--spacing: …` key should make them entirely theme driven instead.
- The default container query variants like `@sm`, `@md`, etc… aren't suggested. Only the `@min-sm` and `@max-sm` style ones are.

Fixes https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1133
Fixes https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1136
Fixes #15811

### CODE REVIEW

**Comment by florianbouvot** [comment]
@thecrypticace can you reorder colors 50 before 100, 200, ...? 

Capture d’écran 2025-01-28 à 15 19 01

**Comment by florianbouvot** [comment]
@thecrypticace I think there are the same issue with spacing

Capture d’écran 2025-01-28 à 15 22 34

File: packages/tailwindcss/src/intellisense.ts [hunk 1]
```diff
@@ -33,7 +34,7 @@ export function getClassList(design: DesignSystem): ClassEntry[] {
     }
   }
 
-  list.sort((a, b) => (a[0] === b[0] ? 0 : a[0] < b[0] ? -1 : 1))
+  list.sort(([a], [b]) => compare(a, b))
```
Comment (RobinMalfait) [inline packages/tailwindcss/src/intellisense.ts:37]: I added this, but I wonder if it's better todo this instead:
```suggestion
  list.sort((a, b) => compare(a[0], b[0]))
```
🤔

**Review by RobinMalfait — APPROVED** [review]
