### PR TITLE
Fix bug with nested @apply rules in utility classes (#17924)

### LINKED ISSUE #17924: @apply referencing another @utility breaks @apply in a nested rule
**What version of Tailwind CSS are you using?**

v4.1.5

**What build tool (or framework if it abstracts the build tool) are you using?**

https://play.tailwindcss.com/

**What version of Node.js are you using?**

Not relevant

**What browser are you using?**

Edge Latest Version

**What operating system are you using?**

MacOs

**Reproduction URL**

https://play.tailwindcss.com/oBufuCc0yf

**Describe your issue**

@apply referencing another @utility breaks @apply in a nested rule. 
Problem is that :hover and :disabled inside `base-utility` stopped working when i referenced `base-utility` in a `@apply` of `parent-utility`.

It would be understandable for the styles of `base-utility` to not get applied completely if it were `@apply parent-utility` but the problem is that I'm using `base-utility` in the className and it should not change regardless of where `base-utility` is used.

:hover and :disabled are simple pseudo selectors. Tried with @variant, also does not work for the same reason.

Would not be a problem for me if @variant actually does work. If the @apply is NOT nested inside `base-utility`, it works fine. The part where its not working is only the @apply is inside a nested rule of `base-utility`.

### PR DESCRIPTION
**Pull request by philipp-spiess**
Fixes #17924

When an `@apply` pointed to utility that nested usages of `@apply`, these nested usages were not properly carried through the dependency chain. This was because we were only tracking dependencies on the immediate parent rather than all parents.

To fix this, this PR:

- Modifies the dependency resolution to track dependencies through the entire parent path
- Uses a `walk(…)` for the node replacement logic so that all nested `@apply` usages are also resolved (as these are now tracked in the dependency list anyways

## Test Plan

- Added a regression test for #17924 to the unit tests and ensure existing tests don't break

### CODE REVIEW

File: packages/tailwindcss/src/apply.ts [hunk 1]
```diff
@@ -66,7 +66,12 @@ export function substituteAtApply(ast: AstNode[], designSystem: DesignSystem) {
       parents.add(parent)
 
       for (let dependency of resolveApplyDependencies(node, designSystem)) {
-        dependencies.get(parent).add(dependency)
+        // Mark every parent in the path as having a dependency to that utility.
+        for (let parent of path) {
+          if (parent === node) continue
+          if (!parents.has(parent)) continue
+          dependencies.get(parent).add(dependency)
+        }
```
Comment (RobinMalfait) [inline packages/tailwindcss/src/apply.ts:74]: Ah interesting, I knew we were performing a topological sort already so was confused why this _didn't_ work.

But this makes sense, and tracking the full path also makes sense.

**Review by RobinMalfait — APPROVED** [review]
