### PR TITLE
Fix Ruby files causing the CLI to hang

### LINKED ISSUE #17379: cli hangs on version 4.0.16
**What version of Tailwind CSS are you using?**

v4.0.16

**What build tool (or framework if it abstracts the build tool) are you using?**

tailwind-cli

**What version of Node.js are you using?**

21.7.3

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Describe your issue**

Just noticed this on a deploy to Heroku, our normal build step for Tailwind is hanging.  No issues locally until I force it to install 4.0.16 and then it just hangs.  No errors.  I don't see a debug or verbose output option for the cli so I'm not sure what to do to further troubleshoot.    Adding `"@tailwindcss/cli": "4.0.15"` to package.json, to force a downgrade to 15, and all is well again.

```
npx @tailwindcss/cli -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify
Need to install the following packages:
@tailwindcss/cli@4.0.16
Ok to proceed? (y)
*hangs* here, no output
```

### PR DESCRIPTION
**Pull request by thecrypticace**
Fixes #17379

The preprocessor we added to detect embedded languages uses a back reference and given a long enough file with certain byte / character patterns it'll cause what appears to be an indefinite hang (might just be catastrophically exponential backtracking but not sure)

This replaces the one regex w/ back references with two, anchored, multi-line regexes

Now we search for all the starting & ending delimiters in the file. We then loop over all the starting delimiters, find the paired ending one, and preprocess the content inside

### CODE REVIEW

**Comment by thecrypticace** [comment]
I didn't put this test case in because it's kinda absurd but this froze previously with the old regex — yes the indentation is like that on purpose:
```rust
// https://github.com/tailwindlabs/tailwindcss/issues/17334
#[test]
fn test_wip() {
    let input = r#"
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
<div class="underline underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
        <div class="underline underline underline underline underline underline underline underline underline"></div>
"#;

    Ruby::test_extract_contains(input, vec!["rounded-full", "bg-red-500", "flex"]);
}
```

File: crates/oxide/src/extractor/pre_processors/ruby.rs [hunk 1]
```diff
@@ -4,12 +4,22 @@ use crate::cursor;
 use crate::extractor::bracket_stack;
 use crate::extractor::pre_processors::pre_processor::PreProcessor;
 use crate::scanner::pre_process_input;
-use bstr::ByteSlice;
-use fancy_regex::Regex;
```
Comment (philipp-spiess) [inline crates/oxide/src/extractor/pre_processors/ruby.rs:8]: Can uninstall this now

File: crates/oxide/src/extractor/pre_processors/ruby.rs [hunk 2]
```diff
@@ -25,14 +35,39 @@ impl PreProcessor for Ruby {
...
+            // The languages must match otherwise we haven't found the end
+            let delimiter_end = end.get(1).unwrap().as_str();
+            if delimiter_end != delimiter_start {
+              continue;
+            }
+
+            let body = &content_as_str[body_start..body_end];
+            let replaced = pre_process_input(body.as_bytes(), &lang.to_ascii_lowercase());
+
+            result.replace_range(body_start..body_end, replaced);
```
Comment (philipp-spiess) [inline crates/oxide/src/extractor/pre_processors/ruby.rs:69]: this probably needs a return here otherwise the loop will continue

**Review by philipp-spiess — APPROVED** [review]
