### PR TITLE
Prevent modifying CSS variables in plugins

### LINKED ISSUE #16100: CSS variables created by plugins are modified
**What version of Tailwind CSS are you using?**

v4.0.1

**What operating system are you using?**

macOS

**Reproduction URL**

- Pull tailwindcss project
- Add the test below to `packages/tailwindcss/src/plugin.test.ts`

```diff
diff --git a/packages/tailwindcss/src/plugin.test.ts b/packages/tailwindcss/src/plugin.test.ts
index 9af3a55f..89129df7 100644
--- a/packages/tailwindcss/src/plugin.test.ts
+++ b/packages/tailwindcss/src/plugin.test.ts
@@ -32,6 +32,36 @@ test('plugin', async () => {
   `)
 })
 
+test('plugin CSS variables', async () => {
+  let input = css`
+    @plugin "my-plugin";
+  `
+
+  let compiler = await compile(input, {
+    loadModule: async () => ({
+      module: plugin(function ({ addBase }) {
+        addBase({
+          body: {
+            '--jun-drawerOpen': '1',
+            '--jun-ES-drawerWidth': '18rem',
+          },
+        })
+      }),
+      base: '/root',
+    }),
+  })
+
+  expect(compiler.build([])).toMatchInlineSnapshot(`
+    "@layer base {
+      body {
+        --jun-drawerOpen: 1;
+        --jun-ES-drawerWidth: 18rem;
+      }
+    }
+    "
+  `)
+})
+
 test('plugin.withOptions', async () => {
   let input = css`
     @plugin "my-plugin";

```

Run the test to see the error:

Image

**Describe your issue**

Tailwind CSS should not modify the CSS variables created by plugins.

### PR DESCRIPTION
**Pull request by siriwatknp**
closes #16100

### CODE REVIEW

File: packages/tailwindcss/src/compat/plugin-api.ts [hunk 1]
```diff
@@ -502,9 +502,11 @@ export function objectToAst(rules: CssInJs | CssInJs[]): AstNode[] {
       if (!name.startsWith('--') && value === '@slot') {
         ast.push(rule(name, [atRule('@slot')]))
       } else {
-        // Convert camelCase to kebab-case:
-        // https://github.com/postcss/postcss-js/blob/b3db658b932b42f6ac14ca0b1d50f50c4569805b/parser.js#L30-L35
-        name = name.replace(/([A-Z])/g, '-$1').toLowerCase()
+        if (!name.startsWith('--')) {
```
Comment (philipp-spiess) [inline packages/tailwindcss/src/compat/plugin-api.ts:505]: We have this exact same check three lines above, perhaps we can move it outside the `if` into a variable so we only need to do this computation once? 👍

**Review by philipp-spiess — COMMENTED** [review]
Makes perfect sense, thanks for the contribution! Got some nit inline. Happy to take over and bring it to the finish line though. We'll also want to add a change log entry for this like `Ensure CSS variables declared in JavaScript plugins don't have their casing changed` or so 🙂

File: packages/tailwindcss/src/compat/plugin-api.ts (hunk 1 above)
Comment (RobinMalfait) [reply packages/tailwindcss/src/compat/plugin-api.ts:505]: Another option is to refactor this a little bit:
```ts
      if (!name.startsWith('--')) {
        if (value === '@slot') {
          ast.push(rule(name, [atRule('@slot')]))
          continue
        }

        // Convert camelCase to kebab-case:
        // https://github.com/postcss/postcss-js/blob/b3db658b932b42f6ac14ca0b1d50f50c4569805b/parser.js#L30-L35
        name = name.replace(/([A-Z])/g, '-$1').toLowerCase()
      }

      ast.push(decl(name, String(value)))
```

Comment (RobinMalfait) [reply packages/tailwindcss/src/compat/plugin-api.ts]: Went ahead and pushed this so that we can get it merged today 👍

File: CHANGELOG.md [hunk 2]
```diff
@@ -14,6 +14,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - Refactor gradient implementation to work around [prettier/prettier#17058](https://github.com/prettier/prettier/issues/17058) ([#16072](https://github.com/tailwindlabs/tailwindcss/pull/16072))
 - Vite: Ensure hot-reloading works with SolidStart setups ([#16052](https://github.com/tailwindlabs/tailwindcss/pull/16052))
 - Vite: Fix a crash when starting the development server in SolidStart setups ([#16052](https://github.com/tailwindlabs/tailwindcss/pull/16052))
+- Do not camelCase CSS custom properties ([#16103](https://github.com/tailwindlabs/tailwindcss/pull/16103))
```
Comment (philipp-spiess) [inline CHANGELOG.md:17]:
```suggestion
- Do not camelCase CSS custom properties added by JavaScript plugins ([#16103](https://github.com/tailwindlabs/tailwindcss/pull/16103))
```

Comment (RobinMalfait) [inline CHANGELOG.md:17]:
```suggestion
- Prevent camelCasing CSS custom properties ([#16103](https://github.com/tailwindlabs/tailwindcss/pull/16103))
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -14,6 +14,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - Refactor gradient implementation to work around [prettier/prettier#17058](https://github.com/prettier/prettier/issues/17058) ([#16072](https://github.com/tailwindlabs/tailwindcss/pull/16072))
 - Vite: Ensure hot-reloading works with SolidStart setups ([#16052](https://github.com/tailwindlabs/tailwindcss/pull/16052))
 - Vite: Fix a crash when starting the development server in SolidStart setups ([#16052](https://github.com/tailwindlabs/tailwindcss/pull/16052))
+- Prevent camelCasing CSS custom properties ([#16103](https://github.com/tailwindlabs/tailwindcss/pull/16103))
```
Comment (philipp-spiess) [inline CHANGELOG.md:17]:
```suggestion
- Prevent camelCasing CSS custom properties added by JavaScript plugins ([#16103](https://github.com/tailwindlabs/tailwindcss/pull/16103))
```

**Comment by siriwatknp** [comment]
> Makes perfect sense, thanks for the contribution! Got some nit inline. Happy to take over and bring it to the finish line though. We'll also want to add a change log entry for this like `Ensure CSS variables declared in JavaScript plugins don't have their casing changed` or so 🙂 

Thanks for the fast response!

**Review by RobinMalfait — APPROVED** [review]
