### PR TITLE
Fix CLI client crash when a file is removed before we process the change notification

### LINKED ISSUE #14613: Temporary files created and removed causing cli to crash with ENOENT no such file or directory lstat error
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.26

**What build tool (or framework if it abstracts the build tool) are you using?**

npx @tailwindcss/cli@next -i ./styles.css -o ./wwwroot/dist/styles.css --postcss --watch --verbose

**What version of Node.js are you using?**

v20.9.0

**What operating system are you using?**

Windows

**Describe your issue**

The watcher in the cli crashes quite frequently. It can work for hours so this is not a massive blocker - in general v4 is great!

```
..
Done in 1ms <<< It works for a awhile but then an edit can get this thrown:
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, lstat 'C:\a-full-path\in-a-dotnet-project\1jufg13t.3fy~'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'C:\\a-full-path\\in-a-dotnet-project\\1jufg13t.3fy~'
}
```

The files ending with ~ are not part of my project. I think they are used to swap compiled bits of code when running my dotnet web project and doing hot reload. Or they are just temporary files that exists for a shorter while during compilation/build.

Maybe the error handling can be improved or the list of watched files (if there is one) needs to adapt more quickly on temp files being added and removed in the space?

### PR DESCRIPTION
**Pull request by philipp-spiess**
Fixes #14613

Don't crash when trying to read the modification time of a file that might already be deleted. 

Note: This fix is purely theoretical right now as I wasn't able to reproduce the issue yet.

### CODE REVIEW

File: packages/@tailwindcss-postcss/src/index.ts [hunk 1]
```diff
@@ -106,7 +106,13 @@ function tailwindcss(opts: PluginOptions = {}): AcceptedPlugin {
             files.push(inputFile)
 
             for (let file of files) {
-              let changedTime = fs.statSync(file, { throwIfNoEntry: false })?.mtimeMs ?? null
+              let changedTime: null | number
+              try {
+                changedTime = fs.statSync(file, { throwIfNoEntry: false })?.mtimeMs ?? null
+              } catch {
+                changedTime = null
+              }
```
Comment (thecrypticace) [inline packages/@tailwindcss-postcss/src/index.ts:114]: I'd remove the `throwIfNoEntry` bit since this try catch will result in identical behavior in that case too

Comment (philipp-spiess) [reply packages/@tailwindcss-postcss/src/index.ts:114]: yeah but now I wonder if this really is the reason for the throw at all. Guess I do need to work a bit more on getting a proper repro first.

Comment (philipp-spiess) [reply packages/@tailwindcss-postcss/src/index.ts:114]: Dude I’m stupid I updated the wrong file. I wanted to add the try/catch in `packages/@tailwindcss-cli/src/commands/build/index.ts`. Awkward

File: packages/@tailwindcss-cli/src/commands/build/index.ts [hunk 2]
```diff
@@ -3,7 +3,7 @@ import { compile, env } from '@tailwindcss/node'
 import { clearRequireCache } from '@tailwindcss/node/require-cache'
 import { Scanner, type ChangedContent } from '@tailwindcss/oxide'
 import { Features, transform } from 'lightningcss'
-import { existsSync } from 'node:fs'
+import { existsSync, Stats } from 'node:fs'
```
Comment (thecrypticace) [inline packages/@tailwindcss-cli/src/commands/build/index.ts:6]:
```suggestion
import { existsSync, type Stats } from 'node:fs'
```

File: packages/@tailwindcss-cli/src/commands/build/index.ts [hunk 3]
```diff
@@ -346,8 +346,11 @@ async function createWatchers(dirs: string[], cb: (files: string[]) => void) {
           if (event.type === 'delete') return
 
           // Ignore directory changes. We only care about file changes
-          let stats = await fs.lstat(event.path)
-          if (stats.isDirectory()) {
+          let stats: Stats | null = null
+          try {
+            stats = await fs.lstat(event.path)
+          } catch {}
+          if (stats === null || stats.isDirectory()) {
```
Comment (thecrypticace) [inline packages/@tailwindcss-cli/src/commands/build/index.ts:353]:
```suggestion
          if (!stats || stats.isDirectory()) {
```

Comment (thecrypticace) [reply packages/@tailwindcss-cli/src/commands/build/index.ts:353]: I wonder if we could change this to something like `if (!stats?.isFile()) {`

Not sure if that would break things tho

File: CHANGELOG.md [hunk 4]
```diff
@@ -17,6 +17,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 - Don’t crash when scanning a candidate equal to the configured prefix ([#14588](https://github.com/tailwindlabs/tailwindcss/pull/14588))
 - Ensure there's always a space before `!important` when stringifying CSS ([#14611](https://github.com/tailwindlabs/tailwindcss/pull/14611))
+- Fix an issue that could caused the postcss client to crash when files are deleted
```
Comment (thecrypticace) [inline CHANGELOG.md:20]:
```suggestion
- Fix issue that could cause the CLI to crash when files are deleted while watching ([#14616](https://github.com/tailwindlabs/tailwindcss/pull/14616))
```

**Review by thecrypticace — CHANGES_REQUESTED** [review]
nit: the PR title is wrong — this is about the CLI

File: packages/@tailwindcss-cli/src/commands/build/index.ts (hunk 3 above)
Comment (philipp-spiess) [reply packages/@tailwindcss-cli/src/commands/build/index.ts:353]: Seems correct yep

Comment (philipp-spiess) [reply packages/@tailwindcss-cli/src/commands/build/index.ts]: hm maybe actually not, we probably want to follow symlinks?

File: packages/@tailwindcss-cli/src/commands/build/index.ts [hunk 5]
```diff
@@ -346,8 +346,11 @@ async function createWatchers(dirs: string[], cb: (files: string[]) => void) {
           if (event.type === 'delete') return
 
           // Ignore directory changes. We only care about file changes
-          let stats = await fs.lstat(event.path)
-          if (stats.isDirectory()) {
+          let stats: Stats | null = null
+          try {
+            stats = await fs.lstat(event.path)
+          } catch {}
+          if (!stats?.isFile() || !stats?.isSymbolicLink()) {
```
Comment (thecrypticace) [inline packages/@tailwindcss-cli/src/commands/build/index.ts:353]:
```suggestion
          if (!stats?.isFile() && !stats?.isSymbolicLink()) {
```

**Review by thecrypticace — CHANGES_REQUESTED** [review]
The changelog has some extra stuff in it

**Comment by philipp-spiess** [comment]
@thecrypticace how the hell 🫠  cursed PR

**Comment by philipp-spiess** [comment]
@thecrypticace most changes were actually intended to fix some conflicts that are in main right now but there was one unnecessary duplicate from a previous version somehow 🤷

File: CHANGELOG.md [hunk 6]
```diff
@@ -11,15 +11,17 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
...
 - Ensure there's always a space before `!important` when stringifying CSS ([#14611](https://github.com/tailwindlabs/tailwindcss/pull/14611))
+- Don't set `display: none` on elements that use `hidden="until-found"` ([#14631](https://github.com/tailwindlabs/tailwindcss/pull/14631))
+- Fix issue that could cause the CLI to crash when files are deleted while watching ([#14616](https://github.com/tailwindlabs/tailwindcss/pull/14616))
 - _Upgrade (experimental)_: Ensure CSS before a layer stays unlayered when running codemods ([#14596](https://github.com/tailwindlabs/tailwindcss/pull/14596))
 - _Upgrade (experimental)_: Resolve issues where some prefixed candidates were not properly migrated ([#14600](https://github.com/tailwindlabs/tailwindcss/pull/14600))
-- Don't set `display: none` on elements that use `hidden="until-found"` ([#14631](https://github.com/tailwindlabs/tailwindcss/pull/14631))
+- _Upgrade (experimental)_: Ensure CSS before a layer stays unlayered when running codemods ([#14596](https://github.com/tailwindlabs/tailwindcss/pull/14596))
```
Comment (philipp-spiess) [inline CHANGELOG.md:24]:
```suggestion
```

**Review by thecrypticace — APPROVED** [review]
