### PR TITLE
Ensure arbitrary variables with data types are extracted correctly

### LINKED ISSUE #16983: border-(length:<custom-property>) not working
:root {
  --checkbox-border-width: 1px;
}

I used it like border-(length:--checkbox-border-width) 

But tailwind does not generate border-width:var(--checkbox-border-width)

the same with text-(length:<custom-property>)

What version of Tailwind CSS are you using?
v4.0.10

What build tool (or framework if it abstracts the build tool) are you using?
Vite 6.2.0

What version of Node.js are you using?
v22.8.0

What operating system are you using?
Windows

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #16983

This PR fixes an issue where the arbitrary variable machine did not extract data type correctly.

## Test plan

- Added regression test

### CODE REVIEW

File: crates/oxide/src/extractor/arbitrary_value_machine.rs [hunk 1]
```diff
@@ -176,6 +176,8 @@ mod tests {
                 "[&>[data-slot=icon]:last-child]",
                 vec!["[&>[data-slot=icon]:last-child]"],
             ),
+            // With type hings
```
Comment (RobinMalfait) [inline crates/oxide/src/extractor/arbitrary_value_machine.rs]:
```suggestion
            // With data types
```

**Review by RobinMalfait — APPROVED** [review]
