### PR TITLE
Fix a crash with older Node.js versions

### LINKED ISSUE #14341: [4.0.0-alpha.21] Next.js build fails when imported CSS file with `@import 'tailwindcss';`
> [!NOTE]
> `tailwindcss@4.0.0-alpha.20` works

**What version of Tailwind CSS are you using?**

v4.0.0-alpha.21

**What build tool (or framework if it abstracts the build tool) are you using?**

```
"dependencies": {
  "next": "14.2.7",
  "react": "18.3.1",
  "react-dom": "18.3.1"
},
"devDependencies": {
  "@tailwindcss/postcss": "4.0.0-alpha.21",
  "@types/node": "22.5.3",
  "@types/react": "18.3.5",
  "@types/react-dom": "18.3.0",
  "tailwindcss": "4.0.0-alpha.21",
  "typescript": "5.5.4"
},
```

**What version of Node.js are you using?**

v18.18.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/devjiwonchoi/repro-tailwindcss-next

**Describe your issue**

1. Imported a `globals.css` file at the root `layout.tsx`.
2. `globals.css` includes `@import 'tailwindcss';` at the top.
3.  Build fails with `TypeError: w.register is not a function` error.

Output:

```
> next build

  ▲ Next.js 14.2.7

   Creating an optimized production build ...
Failed to compile.

-- inner error --
TypeError: w.register is not a function
    at Object.<anonymous> (/.../node_modules/@tailwindcss/node/dist/index.js:1:2323)
    at ...

Import trace for requested module:
./app/globals.css

> Build failed because of webpack errors
```

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #14341

### CODE REVIEW

File: packages/@tailwindcss-node/src/index.ts [hunk 1]
```diff
@@ -6,5 +6,5 @@ export * from './compile'
 // not necessary.
 if (!process.versions.bun) {
   let localRequire = Module.createRequire(import.meta.url)
-  Module.register(pathToFileURL(localRequire.resolve('@tailwindcss/node/esm-cache-loader')))
+  Module.register?.(pathToFileURL(localRequire.resolve('@tailwindcss/node/esm-cache-loader')))
```
Comment (thecrypticace) [inline packages/@tailwindcss-node/src/index.ts:9]: Maybe add a comment as to _why_ we're doing the conditional check?

Something like this maybe?

```
// Register was not added until Node v18.19.0 and v20.6.0
// Not calling it means that while ESM dependencies don't get reloaded the actual included files will because they cache bust directly by using `?id=…`
```

Comment (thecrypticace) [reply packages/@tailwindcss-node/src/index.ts:9]: (but appropriately wrapping the comment ofc)

Comment (philipp-spiess) [reply packages/@tailwindcss-node/src/index.ts:14]: Yep, for sure!

**Review by thecrypticace — APPROVED** [review]
