### PR TITLE
Only detect nesting when using `@apply`

### LINKED ISSUE #13317: Tailwind CSS does not work with native nested CSS
**What version of Tailwind CSS are you using?**

3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 5.2.2 and postcss 8.4.38, following the https://tailwindcss.com/docs/guides/vite tutorial

https://caniuse.com/css-nesting

**What version of Node.js are you using?**

v18.14.0

**What browser are you using?**
Firefox 123

**What operating system are you using?**

Windows 11

**Reproduction URL**

A freshly created project, set up according to the guide above. And with a single component that demonstrates the issue
[my-project.zip](https://github.com/tailwindlabs/tailwindcss/files/14720868/my-project.zip)

Steps to reproduce
1. Download it
2. `npm install`
3. `npm run dev`
4. Go to the website
5. The console shows the following warning
```
[vite:css] Nested CSS was detected, but CSS nesting has not been configured correctly.
Please enable a CSS nesting plugin *before* Tailwind in your configuration.
See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting
3  |  .cat {
4  |    background-color: blue;
5  |    & .dog {
   |    ^^^^^^^^
6  |      background-color: red;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^
7  |    }
   |  ^^^
```

**Describe your issue**
When I use nested CSS, which is widely supported https://caniuse.com/css-nesting , TailwindCSS or Vite kicks in and displays a warning. I consider that to be an issue, since I would hope that excellent tools are compatible with the latest browser standards.

### PR DESCRIPTION
**Pull request by RobinMalfait**
Up until now we've detected nesting and warned our users to ensure that they're using a nesting plugin. All major browsers have proper support for native nesting so there is no need for us to keep warning the user about nested CSS at all.

However, there are still cases where nesting is not allowed and that's when you are using `@apply`.

If you are using `@apply foo` where `foo` contains nested CSS, then it will not work as expected, and in this scenario you do need to use a nesting plugin.

If you are using `@apply` and you are not applying any classes with nesting in them, then you are good to go.

Fixes: #13317

### CODE REVIEW

File: src/lib/expandApplyAtRules.js [hunk 1]
```diff
@@ -432,6 +432,23 @@ function processApply(root, context, localCache) {
...
+        rule.walkRules(() => {
+          throw apply.error(
+            [
+              `The \`${applyCandidate}\` class cannot be applied because it uses nested CSS.`,
+              'Please enable a CSS nesting plugin *before* Tailwind in your configuration.',
+              'See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting',
+            ].join('\n')
+          )
+        })
+      }
```
Comment (thecrypticace) [inline src/lib/expandApplyAtRules.js:450]: What if the applied thing is nested _inside_ another rule? Can that happen here? If so we should probably walk rule.parent all the way to the root to detect that.

Comment (thecrypticace) [reply src/lib/expandApplyAtRules.js:450]: You can apply user CSS and that is broken:
1. https://play.tailwindcss.com/MevI8qxvI6?file=css
2. https://play.tailwindcss.com/sdpYgh5nZS?file=css

Comment (RobinMalfait) [reply src/lib/expandApplyAtRules.js:450]: Aha I see what you mean, this should also be solved by this PR already (added an additional test to proof it). The reason why it works I think is because if you have `.foo .bar {}` we register both `foo` and `bar` as applyable candidates pointing to the same node (or a clone)

So if you have `.foo { .bar {} }` both `foo` and `bar` are applyable and point to the same node. I'm not 100% sure on this (my brain is tired lol) but the test I added seems to prove this as well 🤔

**Review by thecrypticace — APPROVED** [review]

File: src/lib/expandApplyAtRules.js [hunk 2]
```diff
@@ -432,6 +432,23 @@ function processApply(root, context, localCache) {
...
+      // Verify that we can apply the class
+      for (let [, rule] of rules) {
+        if (rule.type === 'atrule') {
+          continue
+        }
+
+        rule.walkRules(() => {
+          throw apply.error(
+            [
+              `The \`${applyCandidate}\` class cannot be applied because it uses nested CSS.`,
```
[the remark this answers is not in the document]
Comment (adamwathan) [reply src/lib/expandApplyAtRules.js:444]: Maybe something like:

```
`The \`${applyCandidate}\` class cannot be used with \`@apply\` because \`@apply\` does not currently support nested CSS.`,
'Rewrite the selector without nesting to use it with `@apply`.'
```

File: src/lib/expandApplyAtRules.js [hunk 3]
```diff
@@ -432,6 +432,23 @@ function processApply(root, context, localCache) {
...
+              'Please enable a CSS nesting plugin *before* Tailwind in your configuration.',
+              'See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting',
```
[the remark this answers is not in the document]
Comment (adamwathan) [reply src/lib/expandApplyAtRules.js:446]: Can drop this part with the change above I think.
