### PR TITLE
v3: Allow hyphen character in regex pattern to use support queries as is

### LINKED ISSUE #13594: `supports` variant compiles function syntax incorrectly
**What version of Tailwind CSS are you using?**

v3 and v4

**Reproduction URL**

https://play.tailwindcss.com/ySYgzSn5FT

**Describe your issue**

Classes like `supports-[font-format(opentype)]:grid` generate invalid CSS, because we currently assume that supports values that don't contain `:` are a CSS property and we insert a variable at the end in an attempt to make the query valid:

```css
@supports (font-format(opentype): var(--tw)) {
  .supports-\[font-format\(opentype\)\]\:grid {
    display: grid;
  }
}
```

This isn't a crazy complicated thing to fix but there are a number of test cases to consider:

```
supports-[font-format(opentype)]:grid
supports-[content:"("]:grid
supports-[(display:grid)_and_font-format(opentype)]:grid
```

### PR DESCRIPTION
**Pull request by brandonmcconnell**
This is the v3 equivalent of PR #13596

Matching for the hyphen character in the existing regex to use support queries as-is

Resolves #13594

Tests (w/ updated):
- ✅ `supports-[display:grid]:grid`
- ✅ `supports-[transform-origin:5%_5%]:underline`
- ✅ `supports-[not(foo:bar)]:underline`
- ✅ `supports-[(foo:bar)or(bar:baz)]:underline`
- ✅ `supports-[(foo:bar)and(bar:baz)]:underline`
- ✅ `supports-[(foo:bar)_and_(bar:baz)]:grid`
- ✅ `supports-[(foo:bar)_and_(bar:baz)_or(baz:qux)]:grid`
- ✅ `supports-[container-type]:underline`
- ✅ `supports-grid:underline`
- ✅ `supports-[--test]:flex`
- ✅ `supports-[selector(A_>_B)]:underline`
- ✅ `supports-[font-format(opentype)]:grid`
- ✅ `supports-[font-tech(color-COLRv1)]:flex`

### CODE REVIEW

File: src/corePlugins.js [hunk 1]
```diff
@@ -409,8 +409,8 @@ export let variantPlugins = {
     matchVariant(
       'supports',
       (value = '') => {
-        let check = normalize(value)
-        let isRaw = /^\w*\s*\(/.test(check)
+        let check = value.startsWith('--') ? value : normalize(value)
+        let isRaw = /^[\w-]*\s*\(/.test(check)
```
Comment (brandonmcconnell) [inline src/corePlugins.js:413]: 2 changes made
- added a `value.startsWith('--')` pre-normalization check that operates in line with #13537 to prevent automatic `var(…)` injection when checking support for custom properties
   
   example: `supports-[--test]:flex`:
   - ❌`@supports var(--test)`
   - ✅`@supports (--test: var(--tw))`
- added hyphen-support for regex pattern matching raw `supports` queries

**Comment by brandonmcconnell** [comment]
@adamwathan @RobinMalfait Just a reminder that this PR is ready to merge (after syncing).

Its v4 equivalent was merged via #13596.

**Review by RobinMalfait — APPROVED** [review]
Thanks for the PR! 💪

**Comment by brandonmcconnell** [comment]
@RobinMalfait Sure thing. I saw Adam mentioned ([here](https://github.com/tailwindlabs/tailwindcss/issues/13594#issuecomment-2619825533)) that he was still seeing the issue in his testing. Were you able to verify my fix on your end?
