### PR TITLE
Show Lightning CSS warnings when optimizing/minifying in production

### LINKED ISSUE #15872: v4: @tailwindcss/vite: Invalid css in @theme section causes the styles to be silently broken in production build only
**What version of Tailwind CSS are you using?**

"@tailwindcss/vite": "^4.0.0"

**What build tool (or framework if it abstracts the build tool) are you using?**

"vite": "^6.0.5"

**What version of Node.js are you using?**

v22.13.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/tkafka/tailwind-v4-css-parsing-bug/tree/main

**Describe your issue**

The above demo demonstrates, how a single typo in `@theme` section in `style.css` causes the page to have broken css in production.
The dev build is fine, and there is no error message in production.
This can let to a single typo silently breaking the production.

## Reproduction steps:

1. Install dependencies:

```bash
pnpm install
```

2. Dev build looks fine:

```bash
pnpm dev
```

Image

3. Production build has broken styling, no error is produced:

```bash
pnpm build && pnpm preview
```

Image

This is caused by a typo in `style.css` in `--shadow-inset-bad` - it has invalid `rgb(var(from --color-secondary-500) r g b / 0.08)` instead of `rgb(from var(--color-secondary-500) r g b / 0.08)` (`from` is in the wrong place).

Commenting out the `--shadow-inset-bad` style causes the production build to have a proper styling.

This seems like an error caused by different behavior of css parsing in development vs. in production. I believe that either the parser should work in a same way in development and production mode, or it should report found errors in css.

### PR DESCRIPTION
**Pull request by RobinMalfait**
This PR improves the DX by showing all the Lightning CSS warnings when using a "production" build (or using `--optimize` or `--minify` flags when using the CLI).

Right now Tailwind CSS itself doesn't care about the exact syntax you are using in the CSS as long as it looks valid. We do this because otherwise we would have to parse a lot more CSS syntax and validate it even though it would be valid CSS in 99.99% of the cases.

Even worse, if you want to use newer CSS syntax that Tailwind CSS doesn't validate yet, then you would get warnings for valid CSS.

Another reason why we don't do this is because the browser already does a great job at ignoring invalid CSS.

So the linked issue #15872 would still silently fail in development mode. In this case, everything would work, except the shadow with the invalid syntax.

But in production mode, you would now get a proper warning from Lightning CSS, because they try to optimize the CSS and remove invalid CSS.

One potential issue here is that we run Lightning CSS on the generated CSS, not on the input CSS. So the current output shows the warnings in the output CSS not the input CSS. Any thoughts if we would just skip the line numbers?

## Test plan

1. Everything works as before
2. In production mode, you would get warnings printed to the terminal. This is done in `@tailwindcss/node` so the CLI/Vite/PostCSS plugins would all get the same behavior.

Screenshots:

If you have a single issue:
image

If you have multiple issues:
image

Fixes: #15872

### CODE REVIEW

**Comment by RobinMalfait** [comment]
Update: I dropped the line numbers because I think those are more confusing because they don't actually map to the correct spot in the input. So I think just _some_ indication that something went wrong is already a big improvement.

image

File: packages/@tailwindcss-node/src/optimize.ts [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import remapping from '@jridgewell/remapping'
 import { Features, transform } from 'lightningcss'
 import MagicString from 'magic-string'
+import pc from 'picocolors'
```
Comment (philipp-spiess) [inline packages/@tailwindcss-node/src/optimize.ts]: Can we inline this dependency? https://unpkg.com/picocolors@1.1.1/picocolors.js 

Probably don't even need all of the options here

**Review by philipp-spiess — CHANGES_REQUESTED** [review]
Let's not add a new dependency, especially when it's only like 30 LOC

**Comment by philipp-spiess** [comment]
Also I think we probably want a way to silence these warnings, WDYT? Have you tried running e.g. tailwindcss.com CSS through it? Will it cause any unexpected warnings?

File: packages/@tailwindcss-node/src/optimize.ts (hunk 1 above)
Comment (RobinMalfait) [reply packages/@tailwindcss-node/src/optimize.ts]: Inlined it 👍 

Only reason I added the dependency is because we were already using it in other packages (`@tailwindcss/cli` and `@tailwindcss/upgrade`). But since we don't use it in the `@tailwindcss/postcss` or `@tailwindcss/vite`, you're right let's just inline them. If they were used there already it's not a big deal.

**Comment by RobinMalfait** [comment]
> Also I think we probably want a way to silence these warnings, WDYT? Have you tried running e.g. tailwindcss.com CSS through it? Will it cause any unexpected warnings?

You sure? Running it on Tailwind Plus or tailwindcss.com doesn't result in any warnings. The warnings also only show up when using Lightning CSS which is typically only when you explicitly have `--minify` or `--optimize` in the CLI, or if you use `NODE_ENV='production'` in PostCSS / Vite land so it won't spam your development workflow.

**Comment by philipp-spiess** [comment]
Yeah that sounds good then 👍

File: pnpm-lock.yaml [hunk 2]
```diff
@@ -6,39 +6,9 @@ settings:
 
 catalogs:
   default:
-    '@types/node':
```
Comment (RobinMalfait) [inline pnpm-lock.yaml]: Cleaning this up as well because nothing should change here now that I removed the dependency again.

**Review by philipp-spiess — APPROVED** [review]

**Comment by lvzhenbo** [comment]
@RobinMalfait 
The victim of this PR has appeared. When I used both the @apply directive and Vue's deep syntax simultaneously, the warning appeared. I need a way to turn off the warning.
image

**Comment by RobinMalfait** [comment]
@lvzhenbo will be fixed by https://github.com/tailwindlabs/tailwindcss/pull/19094

**Comment by sgarfinkel** [comment]
@RobinMalfait Can you add a way to opt out of the warnings? I'd like to turn them off--they are busy and are being caused by transitives that I can't easily patch or fix. Since these log straight to console there's no particularly easy way to filter them.
