### PR TITLE
Properly skip over nodes when using `replaceNode`

### LINKED ISSUE #16298: [v4] "Maximum call stack size exceeded" when using @resource with @slot
**What version of Tailwind CSS are you using?**

4.0.3

**What build tool (or framework if it abstracts the build tool) are you using?**

angular: 19.1.4, tailwindcss: 4.0.3, tailwindcss/postcss: 4.0.3

**What version of Node.js are you using?**

23.7.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/Joxeur2/tailwind-test.git

**Describe your issue**

I have an Angular application that I am migrating to Tailwind 4. I'm also using a purchased theme that is based on Tailwind and has also been migrated to Tailwind 4.
However, when I use the theme, I get the error "Maximum call stack size exceeded."

After some investigation, I managed to reproduce the issue and created a separate repo with minimal setup here: https://github.com/Joxeur2/tailwind-test.git

My problem occurs when these two things are present:

- I use a @resource pointing to my main.css to be able to use @apply
- I use a @slot in main.css

I imagine I could move my @variant along with my @slot into another CSS file and only reference the rest with @resource, but as I mentioned, I am using a purchased theme and I would really hate to have to mess with the theme’s code...

### PR DESCRIPTION
**Pull request by philipp-spiess**
Fixes #16298 

This PR fixes an issue where using an AST walk in combination with `replaceNode` and various `SkipAction` would either cause children to be visited multiple times or not visited at all even though it should. This PR fixes the issue which also means we can get rid of a custom walk for `@variant` inside the `@media` that was used to apply `@variant` because we never recursively visited children inside the `@media` rule.

Because we now can use the regular walk for `@variant`, we now properly convert `@variant` to `@custom-variant` inside `@reference`-ed stylesheet which also fixes #16298

## Test plan

Lots of tests added to ensure the combinations of `WalkAction` and `replaceWith()` works as expected.

### CODE REVIEW

File: packages/tailwindcss/src/ast.ts [hunk 1]
```diff
@@ -137,39 +137,54 @@ export function walk(
     }
 
     path.push(node)
+    let replacedNode = false
```
Comment (RobinMalfait) [inline packages/tailwindcss/src/ast.ts:140]: We probably want to port this behavior to other `walk` implementations in the codebase:

https://github.com/tailwindlabs/tailwindcss/blob/d566dbdef658b8c98a8c596466d74f11c72295e2/packages/tailwindcss/src/compat/selector-parser.ts#L82-L130

and 

https://github.com/tailwindlabs/tailwindcss/blob/d566dbdef658b8c98a8c596466d74f11c72295e2/packages/tailwindcss/src/value-parser.ts#L53-L101

Comment (philipp-spiess) [reply packages/tailwindcss/src/ast.ts:140]: ay

**Review by RobinMalfait — APPROVED** [review]
