### PR TITLE
Fix crash showing completions in Intellisense when using a custom separator

### LINKED ISSUE #894: Config separator not work
**What version of VS Code are you using?**

For example: v1.85.1

**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.10.5

**What version of Tailwind CSS are you using?**

For example: v3.4.0

**What package manager are you using?**

For example: npm

**What operating system are you using?**

 Windows 10

**Tailwind config**

```js
export default {
  content: ["**/*.html"],
  separator:'_', 
} 
```

**VS Code settings**

```json
 // all default config
```

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Describe your issue**

Config separator not work ，hope work when  `separator:'_'`!

### PR DESCRIPTION
**Pull request by thecrypticace**
Intellisense uses the internal `getVariants` API and its use of `__TAILWIND_PLACEHOLDER__` crashes inside Tailwind's variant formatting when the separator is `_`. This crashes the entire completion routine in intellisense and prevents them from appearing.

I've changed it to use no "special" characters to prevent the crash. Instead, we use `TAILWINDPLACEHOLDER` with a unique, random ID attached to eliminate potential conflicts with registered utilities.

Fixes https://github.com/tailwindlabs/tailwindcss-intellisense/issues/894

### CODE REVIEW

File: src/lib/setupContextUtils.js [hunk 1]
```diff
@@ -1054,7 +1059,7 @@ function registerPlugins(plugins, context) {
         values: Object.keys(options.values ?? {}),
         hasDash: name !== '@',
         selectors({ modifier, value } = {}) {
-          let candidate = '__TAILWIND_PLACEHOLDER__'
+          let candidate = `TAILWINDPLACEHOLDER${id}`
```
Comment (RobinMalfait) [inline src/lib/setupContextUtils.js:1062]: I don't love the placeholder, but I didn't love it before either haha. One potential improvement could be to use a UUID (without the `-`) but that's almost overkill for this.

```js
crypto.randomUUID().replaceAll('-','')
```

**Review by RobinMalfait — APPROVED** [review]

File: src/lib/setupContextUtils.js (hunk 1 above)
Comment (thecrypticace) [reply src/lib/setupContextUtils.js:1062]: yeah I really don't like the placeholder either but it's necessary for the current implementation. UUID would definitely be overkill for this.
