### PR TITLE
Don’t split vars with numbers in them inside arbitrary values

### LINKED ISSUE #8079: Tailwind incorrect generate CSS variables as minus sign
**What version of Tailwind CSS are you using?**

3.0.23

Hi,

I am not sure if this issue is linked to the other problems I have reported in #7874 and #7884 as the output issue seems different. I am therefore opening a new issue.

If I use the following CSS:

```
.prose h1 {
    @apply tw-text-[length:var(--heading-h1-font-size)];
  }
```

Tailwind will generate the following code:

```
.prose h1 {
  font-size: var(--heading-h1 - font-size);
}
```

For some reason the dash after the -h1 part is considered as a minus (maybe due to the number ?). In all cases this seems like a bug.

Thanks :)

### PR DESCRIPTION
**Pull request by thecrypticace**
A regex we use to normalize spacing around operators in calc was adding spaces around `-` in `var(…)` when it was preceded by a number. This fixes that problem. We now also have explicit tests for the normalization behavior instead of just pure indirect tests.

Fixes #8079

cc @RobinMalfait I'm not sure I really understand what all is happening here so I would appreciate a quick glance over the code to see if anything jumps out at you

### CODE REVIEW

File: src/util/dataTypes.js [hunk 1]
```diff
@@ -42,10 +42,16 @@ export function normalize(value, isRoot = true) {
...
+  value = value.replace(/calc\(.+\)/g, (match) => {
+    return match.replace(
+      /(-?\d*\.?\d(?!\b-.+[,)](?![^+\-/*])\D)(?:%|[a-z]+)?|\))([+\-/*])/g,
+      '$1 $2 '
+    )
+  })
+
+  // Add spaces around some operators not inside calc() that do not follow an operator
+  // or '('.
+  return value.replace(/(-?\d*\.?\d(?!\b-.+[,)](?![^+\-/*])\D)(?:%|[a-z]+)?|\))([\/])/g, '$1 $2 ')
```
Comment (RobinMalfait) [inline src/util/dataTypes.js:54]: I don't think this is strictly necessary, because `rgba(0 0 0/0.1)` seems to work as expected, but it generates cleaner css!

File: tests/normalize-data-types.test.js [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+    'url("https://example.com/abc+def/some-path/2022-01-01-abc/some_underscoered_path")',
+  ],
+
+  // var(…) is preserved as is
+  ['var(--foo)', 'var(--foo)'],
+  ['var(--headings-h1-size)', 'var(--headings-h1-size)'],
+
+  // calc(…) get's spaces around operators
+  ['calc(1+2)', 'calc(1 + 2)'],
+  ['calc(100%+1rem)', 'calc(100% + 1rem)'],
```
Comment (RobinMalfait) [inline tests/normalize-data-types.test.js:25]: I would maybe add 1 more test with nested `calc` just to verify that that works as well `calc(1+calc(100%-20px))` for example should result in `calc(1 + calc(100% - 20px))`

**Review by RobinMalfait — APPROVED** [review]
This normalize function is normalizing the input we get (from the candidate found in your templates) and produce an actual value. So it has to swap `_` with ` ` for example. The `calc` function in the candidate is defined as `calc(1+1)` but that's not valid css, it has to contain spaces around operators like `calc(1 + 1)` so that's why the code exists there.

As far as I know this is only necessary for the `calc` function to have spaces around operators, but it doesn't hurt to have it on other operators as well for generating cleaner css.

File: src/util/dataTypes.js (hunk 1 above)
Comment (thecrypticace) [reply src/util/dataTypes.js:54]: I did this because we also apply spaces to aspect-[16/9]. I'd rather remove the spaces if that's fine though.

File: tests/normalize-data-types.test.js (hunk 2 above)
Comment (thecrypticace) [reply tests/normalize-data-types.test.js:25]: Added and it works as expected 🎉
