### PR TITLE
Fix cannot read properties of undefined (reading 'modifier')

### LINKED ISSUE #9655: Cannot read properties of undefined (reading 'modifier')
**What version of Tailwind CSS are you using?**

v3.2.1

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 3.1.8

**What version of Node.js are you using?**

v16.17.0

**What browser are you using?**

Chrome, Safari, or N/A

**What operating system are you using?**

Windows

**Describe your issue**

Autocomplete of css class not working in WebStorm (any files) not working, 
embed language server not started with error:
`TypeError: Cannot read properties of undefined (reading 'modifier')\n
					at api.addVariant (c:\\app\\node_modules\\tailwindcss\\lib\\lib\\setupContextUtils.js:578:40)\n
					at c:\\app\\node_modules\\tailwindcss\\lib\\lib\\setupContextUtils.js:538:38\n`

### PR DESCRIPTION
**Pull request by ttkoma**
Fixes: #9655

### CODE REVIEW

File: src/lib/setupContextUtils.js [hunk 1]
```diff
@@ -601,6 +601,10 @@ function buildPluginApi(tailwindConfig, context, { variantList, variantMap, offs
       api.addVariant(
         variant,
         ({ args, container }) => {
+          if (!args) {
+            return null
+          }
+          
           if (args.value === sharedState.NONE && !hasDefault) {
```
Comment (theskollie) [inline src/lib/setupContextUtils.js:608]:
```
if (!args ||  args.value === sharedState.NONE && !hasDefault) {
return null;
}
else {
return undefined;
}

```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your PR!
Much appreciated! 🙏

I've made a few small changes so that it behaves similar to how it behaved before we made those internal changes. Also added a test that verifies this behaviour (without crashing).

Thanks!
