### PR TITLE
Don't read variables for shadow sizes

### LINKED ISSUE #13438: [V4] Box Shadow Color doesn't work
**What version of Tailwind CSS are you using?**

For example: 4.0.0-alpha.11

**What build tool (or framework if it abstracts the build tool) are you using?**

nextjs@14

**What version of Node.js are you using?**

For example: v21.7.1

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: macOS

**Reproduction URL**

https://github.com/alexhtech/tailwindcss4-test

**Describe your issue**

`<div className="h-20 w-20 shadow-xl shadow-red-500" />` - color isn't applied it tends to be `rgba(0,0,0, 0.1)`

### PR DESCRIPTION
**Pull request by adamwathan**
Resolves https://github.com/tailwindlabs/tailwindcss/issues/13438

In https://github.com/tailwindlabs/tailwindcss/pull/13177 we changed the way utility values are referenced in utility classes to use variables with fallbacks instead of raw values:

```diff
  .pt-4 {
-   padding-top: 1rem;
+   padding-top: var(--spacing-4, 1rem);
  }
```

This creates an issue with colored shadows, because colored shadows rely on being able to override the value of a sub-variable that is reference by the actual shadow variable created based on your theme configuration.

Simplified but representative code:

```css
:root {
  --shadow-sm: 0 1px 2px 0 var(--tw-shadow-color, black);
}

.shadow-sm {
  box-shadow: var(--shadow-sm, 0 1px 2px 0 var(--tw-shadow-color, black));
}

.shadow-blue {
  --tw-shadow-color: blue;
}
```

The problem here is that `var(--shadow-sm, ...)` will see that `--shadow-sm` is defined on `:root`, and use the computed value of that variable from `:root`, where `--tw-shadow-color` is yet to be defined, so the color falls back to `black` even when using the `shadow-blue` utility:

```html
<!-- Shadow is still black, not blue like you might expect -->
<div class="shadow-sm shadow-blue">
  <!-- ... -->
</div>
```

This caught me by surprise personally as I expected CSS variables to be evaluated lazily but it seems like they are not. The only solution I've found here is to _not_ reference the `--shadow-sm` variable in the `.shadow-sm` class, to make sure the value of `--tw-shadow-color` on the current element is respected, rather than looking for the value of `--tw-shadow-color` where `--shadow-sm` is defined:

```diff
  :root {
    --shadow-sm: 0 1px 2px 0 var(--tw-shadow-color, black);
  }
  
  .shadow-sm {
-   box-shadow: var(--shadow-sm, 0 1px 2px 0 var(--tw-shadow-color, black));
+   box-shadow: 0 1px 2px 0 var(--tw-shadow-color, black);
  }
  
  .shadow-blue {
    --tw-shadow-color: blue;
  }
```

This is pretty unfortunate because now our box shadow utilities behave subtly differently than every other utility in the framework. I'm hoping we can find some trick to make these variables lazily evaluated, and [tweeted about it](https://twitter.com/adamwathan/status/1775937299919859961) in case someone else out there has any ideas.

For now though we should merge this to effectively selectively revert https://github.com/tailwindlabs/tailwindcss/pull/13177 for the affected utilities.

### CODE REVIEW

File: packages/tailwindcss/src/theme.ts [hunk 1]
```diff
@@ -227,6 +228,7 @@ export type ThemeKey =
   | '--scroll-padding'
   | '--sepia'
   | '--shadow'
+  | `--shadow-${string}`
```
Comment (RobinMalfait) [inline packages/tailwindcss/src/theme.ts:231]: I think a better way of doing this would be to update the `get` function instead:

```diff
-  get(themeKeys: ThemeKey[]): string | null {
+  get(themeKeys: (ThemeKey | `${ThemeKey}-${string}`)[]): string | null {
```

That way you get this for free for every property, but only when using `theme.get`

File: packages/tailwindcss/tests/ui.spec.ts [hunk 2]
```diff
@@ -160,6 +160,33 @@ test('composing shadow, inset shadow, ring, and inset ring', async ({ page }) =>
   )
 })
 
+test('shadow colors', async ({ page }) => {
+  let { getPropertyValue } = await render(
+    page,
+    html`<div id="x" class="shadow shadow-red-500"></div>
+      <div id="y" class="shadow-xl shadow-red-500"></div>`,
```
Comment (thecrypticace) [inline packages/tailwindcss/tests/ui.spec.ts:167]: That is some weird af formatting. Prettier seems to be okay with this too which feels better:

```suggestion
    html`
      <div id="x" class="shadow shadow-red-500"></div>
      <div id="y" class="shadow-xl shadow-red-500"></div>
    `,
```

Comment (adamwathan) [reply packages/tailwindcss/tests/ui.spec.ts]: Nice, tweaked that too 👍

**Review by RobinMalfait — APPROVED** [review]

File: playgrounds/vite/src/app.tsx [hunk 3]
```diff
@@ -2,7 +2,7 @@ import { Foo } from './foo'
 
 export function App() {
   return (
-    <div className="m-3 p-3 border">
+    <div className="m-3 p-3 border shadow-xl shadow-red-500">
```
Comment (RobinMalfait) [inline playgrounds/vite/src/app.tsx:5]: Not sure if you wanted to commit this part. But other than that, looking good!

**Review by thecrypticace — APPROVED** [review]

File: playgrounds/vite/src/app.tsx (hunk 3 above)
Comment (adamwathan) [reply playgrounds/vite/src/app.tsx:5]: Jesus christ how many things can I fuck up in the smallest diff possible?

**Review by RobinMalfait — APPROVED** [review]
