### PR TITLE
Fix `fontSize` array upgrade

### LINKED ISSUE #17622: Upgrade cli does not output line height separately from the fontsize array
**What version of Tailwind CSS are you using?**

v4.1.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 15.2.5

**What version of Node.js are you using?**

For example: v22.14.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Ubuntu Linux (24.10)

**Reproduction URL**

/

**Describe your issue**

In tailwind config, we could do something like this:

```ts
extend: {
  fontSize: {
    "title-custom": ["50px", "62px"]
  }
}
```
Which would generate
```css
.title-custom {
  font-size: 50px;
  line-height: 62px;
}
```
Upgrading to v4, the cli outputs
```css
 --text-title-custom: 50px, 62px;
```
And it does not generate any classes.

**Expected Behaviour**

The cli should treat the second element of the array as line-height and add a new variable for it rather than adding it to one variable separated by a comma.

```css
--text-title-custom: 50px;
--text-title-custom--line-height: 62px;
```

### PR DESCRIPTION
**Pull request by wongjn**
Fixes #17622.

Adds a specific handling case in `themeableValues()` in `packages/tailwindcss/src/compat/apply-config-to-theme.ts`. It seems like this has unique handling in v3 for an array value, whereby the second value is treated as a `line-height`.

### CODE REVIEW

File: packages/tailwindcss/src/compat/apply-config-to-theme.ts [hunk 1]
```diff
@@ -130,7 +130,13 @@ export function themeableValues(config: ResolvedConfig['theme']): [string[], unk
     }
 
     if (Array.isArray(value) && value.every((v) => typeof v === 'string')) {
-      toAdd.push([path, value.join(', ')])
+      if (path[0] === 'fontSize') {
```
Comment (philipp-spiess) [inline packages/tailwindcss/src/compat/apply-config-to-theme.ts:133]:
```suggestion
      if (path[0] === 'fontSize' && value.length === 2) {
```

I'd probably want to make sure this _only_ works for tuples.

File: CHANGELOG.md [hunk 2]
```diff
@@ -12,6 +12,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - Ensure `color-mix(…)` polyfills do not cause used CSS variables to be removed ([#17555](https://github.com/tailwindlabs/tailwindcss/pull/17555))
 - Ensure the `color-mix(…)` polyfill creates fallbacks for theme variables that reference other theme variables ([#17562](https://github.com/tailwindlabs/tailwindcss/pull/17562))
 - Fix brace expansion in `@source inline('z-{10..0}')` with range going down ([#17591](https://github.com/tailwindlabs/tailwindcss/pull/17591))
+- Fix `fontSize` plain array tuple upgrade ([#17630](https://github.com/tailwindlabs/tailwindcss/pull/17630))
```
Comment (philipp-spiess) [inline CHANGELOG.md:15]:
```suggestion
- Ensure compatibility with array tuples used in `fontSize` JS theme keys ([#17630](https://github.com/tailwindlabs/tailwindcss/pull/17630))
```
Not 100% sure about this change but I want to make sure this has to do with JS theme keys so it's clearer who this fix is for. WDYT?

Maybe this is a bit more clear

**Review by philipp-spiess — APPROVED** [review]
Splendid, thanks! I left two questions inline and am curious to know your thoughts about them.

File: packages/tailwindcss/src/compat/apply-config-to-theme.ts (hunk 1 above)
Comment (wongjn) [reply packages/tailwindcss/src/compat/apply-config-to-theme.ts:133]: I think if we are to keep maximum compatibility with v3, we shouldn't restrict to 2 values. In v3, [it still emits `line-height`](https://play.tailwindcss.com/Twg4KzukfM) with > 2 values, though I'm not sure how likely this would have occurred in the real world.

Though thinking about this, perhaps we may need to check that there is **at least** two values for the `value[1]` reference?

File: CHANGELOG.md (hunk 2 above)
Comment (wongjn) [reply CHANGELOG.md:15]: Sure! Perhaps even having two changelog entries? As some may not understand that this also fixes this in the upgrade tool. So have one changelog entry mentioning better compatibility with in JS compate layer and then another entry saying that the `fontSize` array tuple is fixed for the upgrade tool.

Comment (philipp-spiess) [reply CHANGELOG.md:15]: two sound good!

File: packages/tailwindcss/src/compat/apply-config-to-theme.ts (hunk 1 above)
Comment (philipp-spiess) [reply packages/tailwindcss/src/compat/apply-config-to-theme.ts:133]: ah yep let's check for at least 2 entries then

Comment (wongjn) [reply packages/tailwindcss/src/compat/apply-config-to-theme.ts:133]: I've just tested again in v3 and an array value with one element, i.e. `2xl: ['2rem']` actually *unsets* the line-height. I'll assume we want to mirror this behavior as well in the compat layer.

Comment (wongjn) [reply packages/tailwindcss/src/compat/apply-config-to-theme.ts:133]: OK! Sure thing :)
